name: Salesforce CI/CD


on:
push:
branches:
- main


jobs:
deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v3


- name: Install SFDX CLI
run: npm install --global sfdx-cli


- name: Authenticate to Sandbox
run: |
echo "${{ secrets.SF_JWT_KEY }}" > server.key
sfdx auth:jwt:grant \
--clientid ${{ secrets.SF_CONSUMER_KEY }} \
--jwtkeyfile server.key \
--username ${{ secrets.SF_SANDBOX_USERNAME }} \
--instanceurl https://test.salesforce.com \
-a ciSandbox


- name: Deploy to Sandbox
run: sfdx force:source:deploy -p force-app -u ciSandbox
