name: Salesforce CI/CD


on:
push:
branches:
- main


jobs:
deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v3
name: Authenticate to Sandbox
run: |
echo "${{ secrets.SF_JWT_KEY }}" > server.key- name: Authenticate to Sandbox
